/* Generated By:JavaCC: Do not edit this line. BelaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int APAR = 7;
  /** RegularExpression Id. */
  int FPAR = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int PONTOVIRG = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int BOOL = 13;
  /** RegularExpression Id. */
  int VOID = 14;
  /** RegularExpression Id. */
  int IGUAL = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int LEITURA = 19;
  /** RegularExpression Id. */
  int RETORNO = 20;
  /** RegularExpression Id. */
  int IMPRESSAO = 21;
  /** RegularExpression Id. */
  int VERDADEIRO = 22;
  /** RegularExpression Id. */
  int FALSO = 23;
  /** RegularExpression Id. */
  int SOMA = 24;
  /** RegularExpression Id. */
  int SUB = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MAIOR = 31;
  /** RegularExpression Id. */
  int DOISIGUAIS = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int FUN = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"float\"",
    "\"bool\"",
    "\"void\"",
    "\"=\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"readInput\"",
    "\"return\"",
    "\"printLn\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"fun\"",
    "<NUM>",
    "<ID>",
  };

}
